language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  - "2.0"
  - rbx-19mode
env:
  - DB=sqlite
before_install:
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
env:
script:
  - 'cd sample/app_3.2.11 && RAILS_ENV=test bundle exec rake db:create && cd ../../'
  - 'cd sample/app_3.2.11 && RAILS_ENV=test bundle exec rake db:migrate --trace && cd ../../'
  - 'cd sample/app_3.2.11 && bundle exec rake db:test:prepare && cd ../../'
  - bundle exec rake spec

bundler_args: --binstubs=./bundler_stubs
