language: ruby
bundler_args: --binstubs=./bundler_stubs

rvm:
  - "2.0"
  - "1.9.2"
  - "1.9.3"
  - "rbx-19mode"
  - "ruby-head"

env:
  - "SKIP_JASMINE=true"
  - "ALL_IN"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - 'cd sample/app_3.2.11 && RAILS_ENV=test bundle exec rake db:create && cd ../../'
  - 'cd sample/app_3.2.11 && RAILS_ENV=test bundle exec rake db:migrate --trace && cd ../../'
  - 'cd sample/app_3.2.11 && bundle exec rake db:test:prepare && cd ../../'
  - 'bundle exec rake'

matrix:
  exclude:
    - rvm: "rbx-19mode"
      env: "SKIP_JASMINE=true"
    - rvm: "2.0"
      env: "ALL_IN"
    - rvm: "1.9.2"
      env: "ALL_IN"
    - rvm: "1.9.3"
      env: "ALL_IN"
    - rvm: "ruby-head"
      env: "SKIP_JASMINE=true"
  allow_failures:
    - rvm: "ruby-head"
